const theme = {
    ltr: "ltr",
    rtl: "rtl",
    placeholder: "editor-placeholder",
    paragraph: "editor-paragraph mb-2",
    quote: "editor-quote border-l-4 border-gray-300 pl-4 italic text-gray-600 my-4",
    heading: {
        h1: "editor-heading-h1 text-3xl font-bold text-gray-900 mb-4 mt-6",
        h2: "editor-heading-h2 text-2xl font-bold text-gray-800 mb-3 mt-5",
        h3: "editor-heading-h3 text-xl font-bold text-gray-800 mb-2 mt-4",
        h4: "editor-heading-h4 text-lg font-bold text-gray-800 mb-2 mt-3",
        h5: "editor-heading-h5 text-base font-bold text-gray-800 mb-1 mt-2",
    },
    list: {
        nested: {
            listitem: "editor-nested-listitem",
        },
        ol: "editor-list-ol list-decimal list-inside mb-4 ml-4",
        ul: "editor-list-ul list-disc list-inside mb-4 ml-4",
        listitem: "editor-listitem mb-1",
    },
    image: "editor-image",
    link: "editor-link text-blue-600 hover:underline cursor-pointer",
    text: {
        bold: "editor-text-bold font-bold",
        italic: "editor-text-italic italic",
        overflowed: "editor-text-overflowed",
        hashtag: "editor-text-hashtag",
        underline: "editor-text-underline underline",
        strikethrough: "editor-text-strikethrough line-through",
        underlineStrikethrough: "editor-text-underlineStrikethrough underline line-through",
        code: "editor-text-code bg-gray-100 rounded px-1 py-0.5 font-mono text-sm text-red-500",
    },
    code: "editor-code bg-gray-900 text-gray-100 block p-4 rounded-lg font-mono text-sm my-4 overflow-x-auto",
    codeHighlight: {
        atrule: "editor-tokenAttr text-purple-400",
        attr: "editor-tokenAttr text-purple-400",
        boolean: "editor-tokenProperty text-blue-400",
        builtin: "editor-tokenSelector text-green-400",
        cdata: "editor-tokenComment text-gray-500",
        char: "editor-tokenSelector text-green-400",
        class: "editor-tokenFunction text-yellow-400",
        "class-name": "editor-tokenFunction text-yellow-400",
        comment: "editor-tokenComment text-gray-500",
        constant: "editor-tokenProperty text-blue-400",
        deleted: "editor-tokenProperty text-blue-400",
        doctype: "editor-tokenComment text-gray-500",
        entity: "editor-tokenOperator text-white",
        function: "editor-tokenFunction text-yellow-400",
        important: "editor-tokenVariable text-orange-400",
        inserted: "editor-tokenSelector text-green-400",
        keyword: "editor-tokenAttr text-purple-400",
        namespace: "editor-tokenVariable text-orange-400",
        number: "editor-tokenProperty text-blue-400",
        operator: "editor-tokenOperator text-white",
        prolog: "editor-tokenComment text-gray-500",
        property: "editor-tokenProperty text-blue-400",
        punctuation: "editor-tokenPunctuation text-gray-400",
        regex: "editor-tokenVariable text-orange-400",
        selector: "editor-tokenSelector text-green-400",
        string: "editor-tokenSelector text-green-400",
        symbol: "editor-tokenProperty text-blue-400",
        tag: "editor-tokenProperty text-blue-400",
        url: "editor-tokenOperator text-white",
        variable: "editor-tokenVariable text-orange-400",
    },
};

export default theme;
